"""
PulseCommerce data preparation and analytics pipeline.

Run from the repository root:

    python src/prepare_data.py

This pipeline:
1. Generates a raw-data quality report.
2. Cleans the Olist source CSVs into data/processed/.
3. Validates the processed datasets.
4. Builds the analysis-ready sales dataset.
5. Runs the analytics workflows required by the dashboard.
6. Runs final analytical validation.

The MySQL loading script is intentionally not executed here because database
credentials and database state are environment-specific.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_WORKFLOWS = PROJECT_ROOT / "src" / "data"
ANALYTICS_WORKFLOWS = PROJECT_ROOT / "src" / "analytics"

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw" / "olist"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

REQUIRED_RAW_FILES = [
    "olist_customers_dataset.csv",
    "olist_geolocation_dataset.csv",
    "olist_orders_dataset.csv",
    "olist_order_items_dataset.csv",
    "olist_order_payments_dataset.csv",
    "olist_order_reviews_dataset.csv",
    "olist_products_dataset.csv",
    "olist_sellers_dataset.csv",
    "product_category_name_translation.csv",
]

# The order matters because several analytics workflows consume outputs
# generated by earlier workflows.
ANALYTICS_PIPELINE = [
    "build_sales_dataset.py",
    "customer_analysis.py",
    "customer_behavior_analysis.py",
    "cohort_analysis.py",
    "cohort_dashboard.py",
    "delivery_analysis.py",
    "order_basket_analysis.py",
    "payment_analysis.py",
    "product_analysis.py",
    "regional_analysis.py",
    "revenue_analysis.py",
    "review_analysis.py",
    "rfm_analysis.py",
    "rfm_dashboard.py",
    "seller_analysis.py",
    "statistical_analysis.py",
    "executive_kpis.py",
    "final_validation.py",
]


def print_stage(title: str) -> None:
    print("\n" + "=" * 80)
    print(title)
    print("=" * 80)


def run_script(script_path: Path) -> None:
    """Run one existing project workflow with the current Python interpreter."""
    print(f"\n▶ Running: {script_path.relative_to(PROJECT_ROOT)}")

    subprocess.run(
        [sys.executable, str(script_path)],
        cwd=PROJECT_ROOT,
        check=True,
    )


def validate_raw_dataset() -> None:
    """Fail early with a useful message when the Olist dataset is missing."""
    print_stage("RAW DATA CHECK")

    if not RAW_DATA_DIR.exists():
        raise FileNotFoundError(
            f"Raw data directory not found: {RAW_DATA_DIR}\n"
            "Download the Olist dataset and place the CSV files in "
            "data/raw/olist/."
        )

    missing_files = [
        filename
        for filename in REQUIRED_RAW_FILES
        if not (RAW_DATA_DIR / filename).exists()
    ]

    if missing_files:
        missing = "\n".join(f"  - {filename}" for filename in missing_files)
        raise FileNotFoundError(
            "The following required Olist files are missing:\n"
            f"{missing}\n\n"
            "Place all nine source CSV files in data/raw/olist/."
        )

    print(f"Raw dataset found: {RAW_DATA_DIR}")
    print(f"Required files found: {len(REQUIRED_RAW_FILES)}/9")


def main() -> None:
    print_stage("PULSECOMMERCE DATA PREPARATION PIPELINE")

    print(f"Project root     : {PROJECT_ROOT}")
    print(f"Raw data         : {RAW_DATA_DIR}")
    print(f"Processed data   : {PROCESSED_DATA_DIR}")

    validate_raw_dataset()

    PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

    # Generate the existing raw-data quality report.
    run_script(DATA_WORKFLOWS / "data_quality_report.py")

    # Convert raw Olist CSVs into the project's processed datasets.
    run_script(DATA_WORKFLOWS / "clean_data.py")

    # Validate the processed base datasets before analytics begin.
    run_script(DATA_WORKFLOWS / "validate_processed_data.py")

    print_stage("ANALYTICS PIPELINE")

    for script_name in ANALYTICS_PIPELINE:
        run_script(ANALYTICS_WORKFLOWS / script_name)

    print_stage("PIPELINE COMPLETE")

    print("Raw Olist data has been processed successfully.")
    print(f"Processed datasets: {PROCESSED_DATA_DIR}")
    print("\nThe generated analytical datasets are ready for the dashboard.")
    print("\nNext steps:")
    print("  1. Configure MySQL if database access is required.")
    print("  2. Start FastAPI: uvicorn api.main:app --reload")
    print("  3. Start Dash:    python -m dashboard.app")


if __name__ == "__main__":
    main()
